### ISSUE TITLE
JS issue: get method on window.exo

### ISSUE THREAD

**Issue by Aatoz** [Nepeta/Exobar#2]
Working on building an ExoBar theme. I'm running XS 12.1.2 Chimera JB. ExoBar itself works fine, but I can confirm that anything you pass into _.get(...) returns undefined. This even is the case using your example theme.html and copy/pasting your example from the docs i.e. _.get('mobile.network') === undefined. FYI window.exo & _ are NOT undefined, those are good.

Lmk if you need more info.

**Comment by Nepeta** [comment]
@Aatoz If you're running these before Exo sends its first update then it's going to be undefined.

I'd suggest looking into update events instead.

**Comment by Aatoz** [comment]
That works. Thanks!
